      name: Update Sileo Packages

   on:
     push:  # 设置触发事件为向仓库推送代码
       paths:
         - debs/*.deb  # 指定当debs目录下有.deb文件被推送时触发

   jobs:
     update-packages:  # 定义任务名称
       runs-on: ubuntu-latest  # 指定运行任务的虚拟机环境

       steps:
         - name: Checkout Repository
           uses: actions/checkout@v2  # 检出代码到虚拟环境

         - name: Install dpkg
           run: sudo apt-get update && sudo apt-get install -y dpkg  # 安装dpkg工具

         - name: Scan Packages
           run: |
             mkdir -p ./debs
             dpkg-scanpackages -m ./debs /dev/null > Packages  # 扫描debs目录并生成Packages文件
             gzip -f9k Packages  #创建一个gz压缩文件

         - name: Push Update
           run: |
             git config --global user.email "lizi54188@outlook.com"  # 更改为您的邮箱
             git config --global user.name "liyu-qi"  #更改为您的用户名
             git add Packages Packages.gz
             git commit -m "Update Packages"
             git push
           env:  # 设置环境变量
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Actions 提供的token用于权限验证